name: padillaroutea
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.3.1
  objectbox: ^4.0.3
  path_provider: ^2.1.5
  objectbox_flutter_libs: any
  json_annotation: ^4.9.0
  intl: ^0.20.2
  logger: ^2.5.0
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  location: ^8.0.0
  url_launcher: ^6.1.14
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.3
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.4.0
  dart_jsonwebtoken: ^2.16.0
  cryptography: ^2.0.5
  jose: ^0.3.4
  pdf: ^3.11.3
  excel: ^4.0.6
  file_picker: ^9.2.1
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  objectbox_generator: any
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logoU.png
